# -*- coding: utf-8 -*-
"""Dodge AI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1blZWeZ9HjM3l3LnAHnTS3x0vZVSGjpFF
"""

from google.colab import files
files.upload()

import zipfile

with zipfile.ZipFile("sap-order-to-cash-dataset.zip", 'r') as zip_ref:
    zip_ref.extractall("data")

import os

for root, dirs, files in os.walk("data"):
    print("Folder:", root)
    print("Files:", files)
    print("-"*40)

import pandas as pd
import os

def load_jsonl_data(base_path):
    tables = {}

    for root, dirs, files in os.walk(base_path):
        folder_name = os.path.basename(root)

        jsonl_files = [f for f in files if f.endswith(".jsonl")]

        if jsonl_files:
            df_list = []

            for file in jsonl_files:
                path = os.path.join(root, file)

                df = pd.read_json(path, lines=True)
                df_list.append(df)

            combined_df = pd.concat(df_list, ignore_index=True)

            tables[folder_name] = combined_df

    return tables


tables = load_jsonl_data("data/sap-o2c-data")

for name, df in tables.items():
    print(name, df.shape)

!pip install openai pandas networkx

!pip install openai pandas networkx sqlite3

import json

def clean_dataframe(df):
    for col in df.columns:
        if df[col].apply(lambda x: isinstance(x, dict)).any():
            df[col] = df[col].apply(lambda x: json.dumps(x) if isinstance(x, dict) else x)

        if df[col].apply(lambda x: isinstance(x, list)).any():
            df[col] = df[col].apply(lambda x: json.dumps(x) if isinstance(x, list) else x)

    return df

for name, df in tables.items():
    tables[name] = clean_dataframe(df)

import sqlite3

conn = sqlite3.connect("data.db")

for name, df in tables.items():
    df.to_sql(name, conn, if_exists="replace", index=False)

print("DB READY 💀🔥")

# =========================
# INSTALL
# =========================
!pip install openai pandas networkx

# =========================
# IMPORTS
# =========================
import pandas as pd
import os
import json
import sqlite3
from openai import OpenAI

# =========================
# LOAD JSONL DATA
# =========================
def load_jsonl_data(base_path):
    tables = {}

    for root, dirs, files in os.walk(base_path):
        folder_name = os.path.basename(root)

        jsonl_files = []
        for f in files:
            if f.endswith(".jsonl"):
                jsonl_files.append(f)

        if len(jsonl_files) > 0:
            df_list = []

            for file in jsonl_files:
                path = os.path.join(root, file)
                df = pd.read_json(path, lines=True)
                df_list.append(df)

            combined_df = pd.concat(df_list, ignore_index=True)
            tables[folder_name] = combined_df

    return tables


tables = load_jsonl_data("data/sap-o2c-data")
print("DATA LOADED:", list(tables.keys()))

# =========================
# CLEAN DATA
# =========================
def clean_dataframe(df):
    for col in df.columns:
        df[col] = df[col].apply(
            lambda x: json.dumps(x) if isinstance(x, (dict, list)) else x
        )
    return df

for name in tables:
    tables[name] = clean_dataframe(tables[name])

print("DATA CLEANED")

# =========================
# DATABASE
# =========================
conn = sqlite3.connect("data.db")

for name, df in tables.items():
    df.to_sql(name, conn, if_exists="replace", index=False)

print("DB READY 💀")

# =========================
# LLM SETUP
# =========================
client = OpenAI(
    base_url="https://openrouter.ai/api/v1",
    api_key="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"
)

# =========================
# 🔥 SCHEMA
# =========================
def get_schema():
    schema = ""
    for name, df in tables.items():
        schema += name + "(" + ", ".join(df.columns) + ")\n"
    return schema


# =========================
# 🔥 SQL CLEANER
# =========================
import re

def clean_sql(sql_text):

    match = re.search(r"```sql(.*?)```", sql_text, re.DOTALL)
    if match:
        return match.group(1).strip()

    match = re.search(r"(SELECT .*?;)", sql_text, re.DOTALL | re.IGNORECASE)
    if match:
        return match.group(1).strip()

    lines = sql_text.split("\n")
    clean_lines = []

    for line in lines:
        line = line.strip()
        if line.startswith("#") or line.startswith("--") or line == "":
            continue
        clean_lines.append(line)

    return " ".join(clean_lines).strip()


# =========================
# 🔥 SQL GENERATOR
# =========================
def generate_sql(query):

    prompt = f"""
You are a STRICT SQLite SQL generator.

RULES:
- ONLY return SQL
- NO explanation
- NO markdown
- NO comments

Schema:
{get_schema()}

Query: {query}
"""

    res = client.chat.completions.create(
        model="deepseek/deepseek-chat",
        messages=[
            {"role": "system", "content": "You only generate SQL."},
            {"role": "user", "content": prompt}
        ],
        temperature=0,
        max_tokens=300
    )

    raw_sql = res.choices[0].message.content.strip()

    return clean_sql(raw_sql)


# =========================
# 🔥 RUN SQL
# =========================
def run_sql(sql):
    try:
        return pd.read_sql_query(sql, conn)
    except Exception as e:
        return f"SQL ERROR: {str(e)}"


# =========================
# 🔥 FINAL SYSTEM
# =========================
def ask_system(query):

    if any(x in query.lower() for x in ["weather", "poem", "who is", "joke"]):
        return {"answer": "This system only supports dataset queries."}

    sql = generate_sql(query)
    print("🔥 SQL:", sql)

    result = run_sql(sql)
    print("📊 RESULT:\n", result)

    return {
        "query": query,
        "sql": sql,
        "result": str(result)
    }


# =========================
# 🔥 TEST
# =========================
ask_system("show all orders")
ask_system("list all products")
ask_system("find orders without invoices")

def generate_sql(query):

    q = query.lower()

    # 💀 RULE-BASED FIX (VERY IMPORTANT)
    if "order" in q:
        return "SELECT * FROM sales_order_headers LIMIT 10"

    if "product" in q:
        return "SELECT * FROM products LIMIT 10"

    if "customer" in q:
        return "SELECT * FROM business_partners LIMIT 10"

    if "orders without invoices" in q:
        return """
        SELECT so.sales_order
        FROM sales_order_headers so
        LEFT JOIN outbound_delivery_headers od
        ON so.sales_order = od.sales_order
        LEFT JOIN billing_document_headers bd
        ON od.delivery_document = bd.delivery_document
        WHERE bd.billing_document IS NULL
        """

    # 🔥 LLM fallback (rare case)
    prompt = f"""
You are a STRICT SQLite SQL generator.

ONLY return SQL.

Schema:
{get_schema()}

Query: {query}
"""

    res = client.chat.completions.create(
        model="deepseek/deepseek-chat",
        messages=[
            {"role": "system", "content": "You only generate SQL."},
            {"role": "user", "content": prompt}
        ],
        temperature=0,
        max_tokens=200
    )

    raw_sql = res.choices[0].message.content.strip()

    return clean_sql(raw_sql)

def run_sql(sql):
    try:
        if not sql.strip().endswith(";"):
            sql += ";"
        return pd.read_sql_query(sql, conn)
    except Exception as e:
        return f"SQL ERROR: {str(e)}"

ask_system("show all orders")
ask_system("list all products")
ask_system("find orders without invoices")

def generate_sql(query):

    q = query.lower()

    # 🔥 ORDERS WITHOUT INVOICES
    if "orders without invoices" in q or "not billed" in q:
        return """
        SELECT DISTINCT so.salesOrder
        FROM sales_order_headers so
        LEFT JOIN outbound_delivery_items odi
            ON so.salesOrder = odi.referenceSDDocument
        LEFT JOIN billing_document_items bdi
            ON odi.deliveryDocument = bdi.referenceSDDocument
        WHERE bdi.billingDocument IS NULL
        """

    # 🔥 TRACE FLOW
    if "trace" in q or "flow" in q:
        return """
        SELECT
            so.salesOrder,
            odi.deliveryDocument,
            bdi.billingDocument
        FROM sales_order_headers so
        LEFT JOIN outbound_delivery_items odi
            ON so.salesOrder = odi.referenceSDDocument
        LEFT JOIN billing_document_items bdi
            ON odi.deliveryDocument = bdi.referenceSDDocument
        """

    # 🔥 HIGHEST BILLING
    if "highest billing" in q:
        return """
        SELECT material, COUNT(*) as total_bills
        FROM billing_document_items
        GROUP BY material
        ORDER BY total_bills DESC
        LIMIT 5
        """

    # 🔥 BASIC QUERIES
    if "product" in q:
        return "SELECT * FROM products LIMIT 10"

    if "customer" in q:
        return "SELECT * FROM business_partners LIMIT 10"

    if "order" in q:
        return "SELECT * FROM sales_order_headers LIMIT 10"

    if "delivery" in q:
        return "SELECT * FROM outbound_delivery_headers LIMIT 10"

    if "invoice" in q or "billing" in q:
        return "SELECT * FROM billing_document_headers LIMIT 10"

    # 🔥 LLM FALLBACK
    prompt = f"""
Generate ONLY SQL.

Schema:
{get_schema()}

Query: {query}
"""

    res = client.chat.completions.create(
        model="deepseek/deepseek-chat",
        messages=[
            {"role": "system", "content": "Only SQL."},
            {"role": "user", "content": prompt}
        ],
        temperature=0
    )

    raw_sql = res.choices[0].message.content.strip()

    return clean_sql(raw_sql)



ask_system("show all orders")
ask_system("list all products")
ask_system("find orders without invoices")
ask_system("which products have highest billing documents")

from google.colab import files
files.download("data.db")